const GAME_STATUS = {
    WAITING_PLAYERS: 'WAITING_PLAYERS',
    PLAYING: 'PLAYING'
}

const GAME_MATCHMAKING = {
    MIN_PLAYERS: 2,
    MAX_PLAYERS: 3,
    TIMEOUT_TO_START: 30000
}

const TILE_TYPE = {
    COTTAGE: 0,
    VILLAGE: 1
}

module.exports = {
    GAME_STATUS,
    GAME_MATCHMAKING,
    TILE_TYPE
}
