const GAME_MATCHMAKING = {
    MIN_PLAYERS: 2,
    MAX_PLAYERS: 4,
    TIMEOUT_TO_START: 5, // seconds
    TIMEOUT_TO_END: 60 // seconds
}

const BOARD = {
    RANGE_NEIGHBORS: 3,
    COTTAGE_MULTIPLY_NEIGHBORS: 1,
    VILLAGE_MULTIPLY_NEIGHBORS: 2,
    COTTAGE_MULTIPLY: 1,
    VILLAGE_MULTIPLY: 5
}

module.exports = {
    GAME_MATCHMAKING,
    BOARD
}
