const GAME = {
    MIN_PLAYERS: 2,
    MAX_PLAYERS: 4,
    GAME_STARTS_AT: 30, // seconds
    GAME_ENDS_AT: 20 * 60, // seconds
    NEXT_RECRUITMENT: 3 * 60,
    STOP_RECRUITMENT: 30,
    INITIAL_UNITS: 1000,
    TROOPS_ARRIVES_AT: 15
}

const BOARD = {
    RANGE_NEIGHBORS: 3,
    COTTAGE_MULTIPLY_NEIGHBORS: 1,
    VILLAGE_MULTIPLY_NEIGHBORS: 2,
    COTTAGE_MULTIPLY: 1,
    VILLAGE_MULTIPLY: 5
}

module.exports = {
    GAME,
    BOARD
}
